import { PrismaClient } from "@prisma/client";
import { asyncHandler } from "../utils/asyncHandler.js";
import { getAIResponse, generateTitle } from "../services/aiService.js";

const prisma = new PrismaClient();

const getConversations = asyncHandler(async (req, res) => {
  const userId = req.user.id;

  const conversations = await prisma.conversation.findMany({
    where: { userId },
    orderBy: { updatedAt: "desc" },
    include: {
      messages: {
        orderBy: { createdAt: "desc" },
        take: 1
      }
    }
  });

  const formattedConversations = conversations.map(conv => {
    const lastMsg = conv.messages[0];
    let preview = "";
    if (lastMsg) {
      preview = lastMsg.content.length > 60
        ? lastMsg.content.substring(0, 60) + "..."
        : lastMsg.content;
    }
    return {
      id: conv.id,
      title: conv.title,
      summary: conv.summary,
      autoGeneratedTitle: conv.autoGeneratedTitle,
      createdAt: conv.createdAt,
      updatedAt: conv.updatedAt,
      lastMessagePreview: preview
    };
  });

  res.status(200).json(formattedConversations);
});

const getConversationById = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.user.id;

  const conversation = await prisma.conversation.findFirst({
    where: { id, userId }
  });

  if (!conversation) {
    return res.status(404).json({ error: "Conversation not found" });
  }

  const messages = await prisma.message.findMany({
    where: { conversationId: id },
    orderBy: { createdAt: "asc" }
  });

  res.status(200).json({
    conversation,
    messages
  });
});

const createConversation = asyncHandler(async (req, res) => {
  const userId = req.user.id;
  const { title } = req.body;

  const conversation = await prisma.conversation.create({
    data: {
      userId,
      title: title || "Untitled Conversation",
    }
  });

  res.status(201).json(conversation);
});
 
const renameConversation = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { title } = req.body;
  const userId = req.user.id;

  if (!title || title.trim() === "") {
    return res.status(400).json({ error: "Title is required" });
  }

  const conversation = await prisma.conversation.findFirst({
    where: { id, userId }
  });

  if (!conversation) {
    return res.status(404).json({ error: "Conversation not found" });
  }

  const updated = await prisma.conversation.update({
    where: { id },
    data: { title: title.trim() }
  });

  res.status(200).json(updated);
});

const deleteConversation = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.user.id;

  const conversation = await prisma.conversation.findFirst({
    where: { id, userId }
  });

  if (!conversation) {
    return res.status(404).json({ error: "Conversation not found" });
  }

  await prisma.conversation.delete({
    where: { id }
  });

  res.status(200).json({ success: true, message: "Conversation deleted successfully" });
});

const sendMessage = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { message } = req.body;
  const userId = req.user.id;

  if (!message || message.trim() === "") {
    return res.status(400).json({ error: "Message is required" });
  }

  const conversation = await prisma.conversation.findFirst({
    where: { id, userId }
  });

  if (!conversation) {
    return res.status(404).json({ error: "Conversation not found" });
  }

  const userMessage = await prisma.message.create({
    data: {
      conversationId: id,
      role: "user",
      content: message
    }
  });
 
  const history = await prisma.message.findMany({
    where: { conversationId: id },
    orderBy: { createdAt: "asc" }
  });

  const responseText = await getAIResponse(message, history);
 
  const assistantMessage = await prisma.message.create({
    data: {
      conversationId: id,
      role: "assistant",
      content: responseText
    }
  });

  await prisma.conversation.update({
    where: { id },
    data: { updatedAt: new Date() }
  });

  let generatedTitle = null;
  const messageCount = await prisma.message.count({
    where: { conversationId: id }
  });
  if (!conversation.autoGeneratedTitle && messageCount === 2) {
    try {
      generatedTitle = await generateTitle(message, responseText);
      if (generatedTitle) {
        await prisma.conversation.update({
          where: { id },
          data: {
            title: generatedTitle,
            autoGeneratedTitle: true
          }
        });
      }
    } catch (titleError) {
      console.error("Failed to auto-generate conversation title:", titleError);
    }
  }

  res.status(200).json({
    userMessage,
    assistantMessage,
    generatedTitle
  });
});

export {
  getConversations,
  getConversationById,
  createConversation,
  renameConversation,
  deleteConversation,
  sendMessage
};